function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "function_block"};
	this.sidHashMap["function_block"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "function_block:25"};
	this.sidHashMap["function_block:25"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "function_block:30"};
	this.sidHashMap["function_block:30"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S3>"] = {sid: "function_block:36"};
	this.sidHashMap["function_block:36"] = {rtwname: "<S3>"};
	this.rtwnameHashMap["<S4>"] = {sid: "function_block:35"};
	this.sidHashMap["function_block:35"] = {rtwname: "<S4>"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "function_block:5"};
	this.sidHashMap["function_block:5"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Digital Output"] = {sid: "function_block:9"};
	this.sidHashMap["function_block:9"] = {rtwname: "<Root>/Digital Output"};
	this.rtwnameHashMap["<Root>/External Interrupt"] = {sid: "function_block:24"};
	this.sidHashMap["function_block:24"] = {rtwname: "<Root>/External Interrupt"};
	this.rtwnameHashMap["<Root>/Function-Call Subsystem"] = {sid: "function_block:25"};
	this.sidHashMap["function_block:25"] = {rtwname: "<Root>/Function-Call Subsystem"};
	this.rtwnameHashMap["<Root>/MATLAB Function1"] = {sid: "function_block:6"};
	this.sidHashMap["function_block:6"] = {rtwname: "<Root>/MATLAB Function1"};
	this.rtwnameHashMap["<Root>/Signal Builder"] = {sid: "function_block:8"};
	this.sidHashMap["function_block:8"] = {rtwname: "<Root>/Signal Builder"};
	this.rtwnameHashMap["<S1>/function"] = {sid: "function_block:27"};
	this.sidHashMap["function_block:27"] = {rtwname: "<S1>/function"};
	this.rtwnameHashMap["<S1>/Digital Input"] = {sid: "function_block:30"};
	this.sidHashMap["function_block:30"] = {rtwname: "<S1>/Digital Input"};
	this.rtwnameHashMap["<S1>/Digital Output"] = {sid: "function_block:36"};
	this.sidHashMap["function_block:36"] = {rtwname: "<S1>/Digital Output"};
	this.rtwnameHashMap["<S1>/MATLAB Function"] = {sid: "function_block:35"};
	this.sidHashMap["function_block:35"] = {rtwname: "<S1>/MATLAB Function"};
	this.rtwnameHashMap["<S2>/Digital Input"] = {sid: "function_block:30:4"};
	this.sidHashMap["function_block:30:4"] = {rtwname: "<S2>/Digital Input"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "function_block:30:3"};
	this.sidHashMap["function_block:30:3"] = {rtwname: "<S2>/Out1"};
	this.rtwnameHashMap["<S3>/In1"] = {sid: "function_block:36:7"};
	this.sidHashMap["function_block:36:7"] = {rtwname: "<S3>/In1"};
	this.rtwnameHashMap["<S3>/Data Type Conversion"] = {sid: "function_block:36:11"};
	this.sidHashMap["function_block:36:11"] = {rtwname: "<S3>/Data Type Conversion"};
	this.rtwnameHashMap["<S3>/Digital Output"] = {sid: "function_block:36:12"};
	this.sidHashMap["function_block:36:12"] = {rtwname: "<S3>/Digital Output"};
	this.rtwnameHashMap["<S4>:1"] = {sid: "function_block:35:1"};
	this.sidHashMap["function_block:35:1"] = {rtwname: "<S4>:1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
